### ISSUE TITLE
Protonup does not worked

### ISSUE THREAD

**Issue by dtantono** [AUNaseef/protonup#37] opened 2022-10-16 23:18 UTC
Hi
I typed protonup amd the output is:
Ready to download Proton-GE-Proton7-37 
Size      : 397.0 MiB 
Published : 2022-10-05
Continue? (Y/n): y
Downloaded 100.00% - 397.1 MiB / 397.0 MiB   
Traceback (most recent call last):
  File "/home/user/.local/bin/protonup", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/protonup/__init__.py", line 4, in main
    return main()
  File "/home/user/.local/lib/python3.10/site-packages/protonup/cli.py", line 33, in main
    get_proton(version=args.tag, yes=args.yes, dl_only=args.download,
  File "/home/user/.local/lib/python3.10/site-packages/protonup/api.py", line 152, in get_proton
    tarfile.open(destination, "r:gz").extractall(install_directory())
  File "/usr/lib/python3.10/tarfile.py", line 2059, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2100, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2173, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.10/tarfile.py", line 2214, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/home/user/.steam/root/compatibilitytools.d/GE-Proton7-37/files/lib64/wine/vkd3d-proton/libvkd3d-proton-utils-3.dll'

But, even I download the package and exract the file to the ~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d/ manually. it still prompted me to update and does not detect the current release

**Comment by yochananmarqos** [comment] 2022-10-17 22:22
Duplicate of #25

**Closed** 2023-07-01 04:09 UTC
